import React, { useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import './styles.css';
const agents=[['ATLAS','Director','ONLINE'],['FORGE','Operations','READY'],['SENTINEL','Quality Control','READY'],['MERCURY','Discovery','MONITORING'],['ECHO','Facebook Discovery','MONITORING'],['HERITAGE','Estate Intelligence','READY']];
function App(){
 const [health,setHealth]=useState(null),[diag,setDiag]=useState(null),[command,setCommand]=useState(''),[result,setResult]=useState('System standing by.');
 const refresh=async()=>{const h=await window.missionControl.health();setHealth(h);setDiag(h.diagnostic)};
 useEffect(()=>{refresh();const t=setInterval(refresh,30000);return()=>clearInterval(t)},[]);
 const run=async e=>{e.preventDefault();if(!command.trim())return;const r=await window.missionControl.command(command);setResult(r.type==='message'?r.data:JSON.stringify(r.data,null,2));setCommand('');refresh()};
 const runDiagnostics=async()=>{const d=await window.missionControl.diagnostics();setDiag(d);setResult(JSON.stringify(d,null,2));}; const git=health?.git;
 return <main><header><div><div className="eyebrow">CHICAS MAP</div><h1>MISSION CONTROL <span>🐕</span></h1></div><div className="status"><b>● SYSTEM</b> {health?.online?'ONLINE':'CHECKING'} <b>● GIT</b> {git?.clean?'CLEAN':'CHANGES'} <b>● SENTINEL</b> {diag?.fail?'BLOCKED':'READY'}</div></header>
 <section className="command"><form onSubmit={run}><input value={command} onChange={e=>setCommand(e.target.value)} placeholder="What is the mission? Example: Why is the map broken?"/><button>RUN MISSION</button></form><small>Try: diagnostics · why is the map broken · audit map layers · git status</small></section>
 <section className="grid metrics"><Card title="SYSTEM SCORE" value={diag?`${diag.score}%`:'—'} detail={diag?.fail?`${diag.fail} failure(s) detected`:'No blocking failures'} /><Card title="MAP FILES" value={health?.counts.mapFiles??'—'} detail={`${health?.counts.kmlFiles??0} KML • ${health?.counts.geojsonFiles??0} GeoJSON/JSON`} /><Card title="DATA FILES" value={health?.counts.dataFiles??'—'} detail="Intelligence sources"/><Card title="UNCOMMITTED" value={git?git.changes.length:'—'} detail={git?.clean?'Working tree clean':'Needs attention'}/></section>
 <section className="grid two"><Panel title="SENTINEL DIAGNOSTIC ENGINE"><div className="diagnostic-head"><strong>{diag?`${diag.score}% HEALTH`:'SCANNING'}</strong><button onClick={runDiagnostics}>RUN FULL DIAGNOSTICS</button></div>{diag?.checks?.map((c,i)=><div className="check" key={i}><b className={c.level.toLowerCase()}>{c.level}</b><span>{c.name}</span><small>{c.detail}</small></div>)}</Panel><Panel title="SWARM STATUS"><div className="agents">{agents.map(([name,role,state])=><div className="agent" key={name}><span className="dot">●</span><div><b>{name}</b><small>{role}</small></div><em>{state}</em></div>)}</div></Panel></section>
 <section className="grid two"><Panel title="GIT INTELLIGENCE"><div className="git"><p><b>Branch:</b> {git?.branch||'Loading...'}</p><p><b>Sync:</b> ↑ {git?.ahead??0} ahead · ↓ {git?.behind??0} behind</p><p><b>Last commit:</b> {git?.lastCommit||'Loading...'}</p><h3>Changed files</h3>{git?.changes?.length?<ul>{git.changes.map((x,i)=><li key={i}>{x}</li>)}</ul>:<p className="quiet">No uncommitted changes.</p>}</div></Panel><Panel title="MISSION QUEUE"><ul className="queue"><li><span>01</span> Audit map data pipeline</li><li><span>02</span> Verify Sentinel publish gate</li><li><span>03</span> Inspect school-zone coverage</li><li><span>04</span> Prepare weekend forecast</li></ul></Panel></section>
 <section className="grid"><Panel title="COMMAND OUTPUT"><pre>{result}</pre></Panel></section><footer><button onClick={refresh}>REFRESH INTELLIGENCE</button><span>Local diagnostics • Sentinel blocks attention-worthy failures</span></footer></main>}
function Card({title,value,detail}){return <article className="card"><small>{title}</small><strong>{value}</strong><span>{detail}</span></article>} function Panel({title,children}){return <article className="panel"><h2>{title}</h2>{children}</article>} createRoot(document.getElementById('root')).render(<App/>);
