import React,{useEffect,useState}from 'react';
import {createRoot}from 'react-dom/client';
import './styles.css';
const agents=[['ATLAS','Director','ONLINE'],['FORGE','Operations','READY'],['SENTINEL','Quality Control','READY'],['MERCURY','Discovery','MONITORING'],['ECHO','Facebook Discovery','MONITORING'],['HERITAGE','Estate Intelligence','READY']];
function App(){
 const [health,setHealth]=useState(null),[diag,setDiag]=useState(null),[command,setCommand]=useState(''),[result,setResult]=useState('System standing by.'),[busy,setBusy]=useState(false),[connection,setConnection]=useState('CONNECTING');
 const [contacts,setContacts]=useState([]),[contact,setContact]=useState({name:'',email:''}),[mail,setMail]=useState({to:'',subject:'',body:''}),[inbox,setInbox]=useState([]),[leads,setLeads]=useState([]),[logo,setLogo]=useState(null);
 const refresh=async()=>{setBusy(true);try{const h=await window.missionControl.health();setHealth(h);setDiag(h.diagnostic);setConnection('CONNECTED')}catch(e){setConnection('ERROR');setResult(`Connection error: ${e.message}`)}finally{setBusy(false)}};
 const loadContacts=async()=>{try{setContacts(await window.missionControl.contacts.list())}catch(e){setResult(`Contacts failed: ${e.message}`)}};
 useEffect(()=>{refresh();loadContacts();const t=setInterval(refresh,30000);return()=>clearInterval(t)},[]);
 const run=async()=>{if(!command.trim()||busy)return;setBusy(true);setResult('Running mission...');try{const r=await window.missionControl.command(command);setResult(r.type==='message'?r.data:JSON.stringify(r.data,null,2));setCommand('');await refresh()}catch(e){setResult(`Mission failed: ${e.message}`)}finally{setBusy(false)}};
 const runDiagnostics=async()=>{if(busy)return;setBusy(true);setResult('Sentinel is running full diagnostics...');try{const d=await window.missionControl.diagnostics();setDiag(d);setResult(JSON.stringify(d,null,2))}catch(e){setResult(`Diagnostics failed: ${e.message}`)}finally{setBusy(false)}};
 const testConnection=async()=>{setResult('Testing Mission Control connection...');try{const r=await window.missionControl.ping();setConnection('CONNECTED');setResult(`Connection confirmed at ${r.time}`)}catch(e){setConnection('ERROR');setResult(`Connection failed: ${e.message}`)}};
 const addContact=async()=>{try{const list=await window.missionControl.contacts.add(contact);setContacts(list);setContact({name:'',email:''});setResult('Contact added to Chica Mission Control.')}catch(e){setResult(`Contact failed: ${e.message}`)}};
 const sendEmail=async()=>{try{setResult('Opening macOS Mail to send...');const r=await window.missionControl.email.send(mail);setResult(r.ok?'Email sent through macOS Mail.':`Mail failed: ${r.error||'unknown error'}`)}catch(e){setResult(`Mail failed: ${e.message}`)}};
 const loadInbox=async()=>{try{setResult('Reading recent messages from macOS Mail...');const m=await window.missionControl.email.inbox(25);setInbox(m);setResult(`Loaded ${m.length} recent inbox messages.`)}catch(e){setResult(`Inbox access failed: ${e.message}. If macOS asks, allow Chica Mission Control to control Mail.`)}};
 const scanInbox=async()=>{try{setResult('Scanning recent email headers for new data...');const r=await window.missionControl.email.scanData(50);setInbox(r.messages);setLeads(r.leads);setResult(`Scan complete: ${r.messages.length} messages, ${r.leads.length} data leads found.`)}catch(e){setResult(`Email scan failed: ${e.message}`)}};
 const chooseLogo=async()=>{try{const file=await window.missionControl.branding.chooseLogo();if(file){setLogo(file);setResult('Exact Chica logo loaded into Mission Control.')}}catch(e){setResult(`Logo import failed: ${e.message}`)}};
 const git=health?.git;
 return <main>
 <header className="hero"><div className="brand"><div className="logo-wrap">{logo?<img src={logo} alt="Chica logo"/>:<div className="logo-fallback">🐕</div>}<button type="button" className="logo-button" onClick={chooseLogo}>USE CHICA LOGO</button></div><div><div className="eyebrow">CHICAS MAP • OPERATIONS CENTER</div><h1>MISSION CONTROL</h1><p className="tagline">See the mission. Run the system. Control the data.</p></div></div><div className="status"><button type="button" onClick={testConnection}>● {connection}</button><b>● SYSTEM</b> {health?.online?'ONLINE':'CHECKING'} <b>● GIT</b> {git?.clean?'CLEAN':'CHANGES'} <b>● SENTINEL</b> {diag?.fail?'BLOCKED':'READY'}</div></header>
 <section className="command"><div className="command-form"><input value={command} onChange={e=>setCommand(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')run()}} placeholder="What is the mission? Example: scan email for new sale data" disabled={busy}/><button type="button" onClick={run} disabled={busy}>{busy?'WORKING...':'RUN MISSION'}</button></div><small>Try: diagnostics · why is the map broken · scan email · audit map layers · git status</small></section>
 <section className="grid metrics"><Card title="SYSTEM SCORE" value={diag?`${diag.score}%`:'—'} detail={diag?.fail?`${diag.fail} failure(s) detected`:'No blocking failures'}/><Card title="MAP FILES" value={health?.counts.mapFiles??'—'} detail={`${health?.counts.kmlFiles??0} KML • ${health?.counts.geojsonFiles??0} GeoJSON/JSON`}/><Card title="DATA FILES" value={health?.counts.dataFiles??'—'} detail="Intelligence sources"/><Card title="UNCOMMITTED" value={git?git.changes.length:'—'} detail={git?.clean?'Working tree clean':'Needs attention'}/></section>
 <section className="grid two"><Panel title="EMAIL COMMAND CENTER"><div className="email-actions"><button type="button" onClick={loadInbox}>READ INBOX</button><button type="button" onClick={scanInbox}>SCAN FOR NEW DATA</button></div><div className="mail-form"><input value={mail.to} onChange={e=>setMail({...mail,to:e.target.value})} placeholder="To"/><input value={mail.subject} onChange={e=>setMail({...mail,subject:e.target.value})} placeholder="Subject"/><textarea value={mail.body} onChange={e=>setMail({...mail,body:e.target.value})} placeholder="Message"/><button type="button" onClick={sendEmail}>SEND EMAIL</button></div><div className="mini-list">{inbox.slice(0,5).map(m=><div key={m.id}><b>{m.from}</b><span>{m.subject}</span></div>)||null}{!inbox.length&&<p className="quiet">No messages loaded yet.</p>}</div></Panel><Panel title="CONTACTS & NAMES"><div className="contact-form"><input value={contact.name} onChange={e=>setContact({...contact,name:e.target.value})} placeholder="Name"/><input value={contact.email} onChange={e=>setContact({...contact,email:e.target.value})} placeholder="Email address"/><button type="button" onClick={addContact}>ADD NAME</button></div><div className="mini-list">{contacts.map(c=><div key={c.id}><b>{c.name||'Unnamed'}</b><span>{c.email}</span></div>)}{!contacts.length&&<p className="quiet">Your Chica contact book is empty.</p>}</div></Panel></section>
 <section className="grid two"><Panel title="EMAIL DATA LEADS"><p className="quiet">Current scanner extracts emails, phone numbers, and date-like leads from recent sender/subject data. Body-level extraction is the next upgrade.</p><div className="mini-list">{leads.slice(0,12).map((x,i)=><div key={i}><b>{x.type.toUpperCase()}: {x.value}</b><span>{x.subject}</span></div>)}{!leads.length&&<p className="quiet">Run SCAN FOR NEW DATA to populate leads.</p>}</div></Panel><Panel title="SENTINEL DIAGNOSTIC ENGINE"><div className="diagnostic-head"><strong>{diag?`${diag.score}% HEALTH`:'SCANNING'}</strong><button type="button" onClick={runDiagnostics} disabled={busy}>RUN FULL DIAGNOSTICS</button></div>{diag?.checks?.map((c,i)=><div className="check" key={i}><b className={c.level.toLowerCase()}>{c.level}</b><span>{c.name}</span><small>{c.detail}</small></div>)}</Panel></section>
 <section className="grid two"><Panel title="SWARM STATUS"><div className="agents">{agents.map(([name,role,state])=><div className="agent" key={name}><span className="dot">●</span><div><b>{name}</b><small>{role}</small></div><em>{state}</em></div>)}</div></Panel><Panel title="GIT INTELLIGENCE"><div className="git"><p><b>Branch:</b> {git?.branch||'Loading...'}</p><p><b>Sync:</b> ↑ {git?.ahead??0} ahead · ↓ {git?.behind??0} behind</p><p><b>Last commit:</b> {git?.lastCommit||'Loading...'}</p><h3>Changed files</h3>{git?.changes?.length?<ul>{git.changes.map((x,i)=><li key={i}>{x}</li>)}</ul>:<p className="quiet">No uncommitted changes.</p>}</div></Panel></section>
 <section className="grid"><Panel title="COMMAND OUTPUT"><pre>{result}</pre></Panel></section><footer><button type="button" onClick={refresh} disabled={busy}>REFRESH INTELLIGENCE</button><span>Local diagnostics • macOS Mail control • Chica data operations</span></footer></main>}
function Card({title,value,detail}){return <article className="card"><small>{title}</small><strong>{value}</strong><span>{detail}</span></article>};function Panel({title,children}){return <article className="panel"><h2>{title}</h2>{children}</article>};createRoot(document.getElementById('root')).render(<App/>);
